[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
fxhash = "0.2.1"
itertools = "0.13.0"
regex = "1.11.1"


[profile.release]
debug = true
